/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./script/GameView"
import Director from "./script/Director"
import StartGame from "./script/StartGame"
import Brids from "./script/Brids"
import Pencel from "./script/Pencel"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/GameView.js",GameView);
		reg("script/Director.js",Director);
		reg("script/StartGame.js",StartGame);
		reg("script/Brids.js",Brids);
		reg("script/Pencel.js",Pencel);
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "GameView.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
